### PR TITLE
Remove Orbit bundles as we use Central ones (cont'd)

### PR DESCRIPTION
**Pull request by mickaelistria**
Some forgotten Orbit bundles are now removed.

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by HannesWell** [comment]
@iloveeclipse IIRC you are a JDT commiter?
So you could help to speed up https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/389 if you merge this one.

It looks like that this is the continuation of https://github.com/eclipse-jdt/eclipse.jdt/pull/27.

**Comment by iloveeclipse** [comment]
> @iloveeclipse IIRC you are a JDT commiter? So you could help to speed up [eclipse-platform/eclipse.platform.releng.aggregator#389](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/389) if you merge this one.
> 
> It looks like that this is the continuation of #27.

If I only knew from the PR description what is the purpose of this PR. **Why** should they be removed at all?
I see that the `org.junit.jupiter.api` to be removed has different bundle version compared with `junit.jupiter.api` (if that is the correct replacement) - 5.8.1 vs 5.8.2. Not sure if that is intended or not, I assume not.
I honestly don't want to merge anything I have no idea what that is and if that is valid patch or not.

**Comment by rgrunber** [comment]
Yeah, when I look inside the generated feature for `org.eclipse.jdt-feature/target/org.eclipse.jdt-3.18.1300-SNAPSHOT.jar` I see :

```
<plugin
         id="org.junit.jupiter.api"
         download-size="219"
         install-size="467"
         version="5.8.1.v20211018-1956"
         unpack="false"/>

<plugin
         id="junit-jupiter-api"
         download-size="188"
         install-size="395"
         version="5.8.2"
         unpack="false"/>
```

There are some other maven central artifacts that vary between 5.8.1 & 5.8.2.

Looking in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target , it should all be 5.8.1 though right ? Is seeing 5.8.2 in a build expected ?

From a legal perspective it's fine because a CQ isn't required for a service release bump but the inconsistency seems a bit weird.

**Comment by mickaelistria** [comment]
At the moment, a mixture of versions is fine as long as it's legal (it is and we have automation to verify that) and tests work.
As soon as we're done removing Orbit's bundle, wr'll update the .target to use 5.8.2 only.

**Review by rgrunber — APPROVED** [review]
LGTM. The feature no longer includes the Orbit bundle.

**Pull request merged**
