### PR TITLE
Set project encoding to UTF-8

### PR DESCRIPTION
**Pull request by fedejeanne**
It was done using a "Quick Fix" and the value set (UTF-8) is the same value that any other project in the workspace uses. The objective of this commit is to declutter the "Problems" view.

### CODE REVIEW

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
You are adding settings to something that is not even a project!

**Comment by fedejeanne** [comment]
> You are adding settings to something that is not even a project!

Technically, it is a project:

grafik

It's the parent maven project, a "POM" project.

Do you think the logic in the `ValidateProjectEncoding` (see [this comment](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/902#discussion_r1382151432)) should be changed?

**Comment by iloveeclipse** [comment]
> It's the parent maven project, a "POM" project.

Sure, but not an **Eclipse** project.


> Do you think the logic in the `ValidateProjectEncoding` (see [this comment](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/902#discussion_r1382151432)) should be changed?

No, I think the logic is fine. You should simply not import this **folder** as an **Eclipse project**.

**Comment by fedejeanne** [comment]
> > It's the parent maven project, a "POM" project.
> 
> Sure, but not an **Eclipse** project.

I see, I will withdraw this PR. I still think that if this is the criteria then the `ValidateProjectEncoding` should at least check the `nature` of the project and exclude the "pure Maven" projects with a POM-packaging, don't you think?

> > Do you think the logic in the `ValidateProjectEncoding` (see [this comment](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/902#discussion_r1382151432)) should be changed?
> 
> No, I think the logic is fine. You should simply not import this **folder** as an **Eclipse project**.

I didn't import them myself, I used the installer (see [comment](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/902#discussion_r1382172743). I hope Ed can fix the issue to prevent this in the future :-)

**Comment by iloveeclipse** [comment]
You didn't get it. This is not a project because in git, there is no ".project" file.
And once again, ValidateProjectEncoding logic is fine. The problem is that you seem to imported lot of **folders** as **projects**. Once you do that, **locally** you personally have **projects**, where in reality there shouldn't be a project at all.

**Comment by fedejeanne** [comment]
👍 

>  The problem is that you seem to imported lot of folders as projects.

Odd, I wasn't even aware that was possible. Thank you for the clarification!

**Pull request closed without merging**
