### PR TITLE
Update target platform's junit dependencies to the latest available

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/799

### CODE REVIEW

**Comment by akurtakov** [comment]
No point, feel free to push.

**Comment by merks** [comment]
Wow, JDT sure builds fast!!  So the question is kind moot!!

@akurtakov 

I am not a committer so I cannot merge this.

I'm out for a while.  Can I ping you in about 2 hours to merge this then so that I can do the follow up activities immediately afterwards?

**Comment by akurtakov** [comment]
I'm not a committer either. Let's hope that @iloveeclipse can act fast enough.

**Comment by iloveeclipse** [comment]
@merks : should I merge that now or should I wait for you to ping me?

**Comment by merks** [comment]
@iloveeclipse   Ping.  I'm back early.  Please merge now.

**Pull request merged**
