### PR TITLE
Add JUnit 5 from Maven Central

### PR DESCRIPTION
**Pull request by mickaelistria**
## Author checklist

- I have thoroughly tested my changes
- The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by mickaelistria** [comment]
@sravanlakkimsetti Can you please review (and merge if it's ok with you)?

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti Can you please review (and merge if it's ok with you)?

Any other pr that needs to be merged along with this one? I think we should merge all together. If this can go independently please let me know

**Comment by mickaelistria** [comment]
This one can go independently. There will be other PR later to remove the Orbit artifact when we think we're done with them.

**Comment by mickaelistria** [comment]
Thanks!

**Pull request merged**
